name: Java CI/CD with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USER: devopsgoofy
      DOCKER_IMAGE_NAME: maven-proj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Increment version
        id: versioning
        uses: oss-actions/auto-semver@v0.1.11
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          type: patch
          
      - name: Print previous and next semver version
        if: github.ref != steps.versioning.outputs.previous_version_ref
        env:
          NEXT_VERSION: ${{ steps.versioning.outputs.version }}
          PREVIOUS_VERSION: ${{ steps.versioning.outputs.previous_version }}
        run: |
          echo "Previous version is $PREVIOUS_VERSION"
          echo "Next version is $NEXT_VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Publish Docker image
        uses: docker/build-push-action@23c657a01f105567f668c7596ce8e5a038da2555 # V6.7.0
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.versioning.outputs.version }}
          build-args: |
            JAR_VERSION=${{ steps.versioning.outputs.version }}
          push: true

      - name: Run Docker container
        run: |
          docker run --rm ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.versioning.outputs.version }}
